# limitations under the License.

---
driver:
  name: "terraform"
  command_timeout: 1800

provisioner:
  name: "terraform"

platforms:
  - name: local

suites:
  - name: "simple_example"
    lifecycle:
      pre_create:
        - ./test/fixtures/all_examples/build_image.sh simple_example
    driver:
      name: "terraform"
      command_timeout: 1800
      root_module_directory: test/fixtures/simple_example
    verifier:
      name: terraform
      color: false
      systems:
        - name: simple_example
          backend: gcp
          shell: true
          controls:
            - gcloud
        - name: jenkins
          backend: ssh
          controls:
            - jenkins
          hosts_output: jenkins_instance_public_ip
          key_files:
            - ./test/fixtures/simple_example/ssh/key
          user: user
    provisioner:
      name: terraform
